name: Tests
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: 'Create env file'
        run: |
          touch .env
          echo "${{ secrets.env }}" > .env
          cat .env
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - uses: jongwooo/next-cache@v1
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Build apps
        run: pnpm build
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start
          command: pnpm test-ci